package com.furandfeathers.enums;

public enum ActionType {
    USER_CREATED,
    USER_UPDATED,
    USER_SUSPENDED,
    USER_ACTIVATED,
    USER_DELETED,
    SHELTER_APPROVED,
    SHELTER_REJECTED,
    SHELTER_SUSPENDED,
    PET_APPROVED,
    PET_REJECTED,
    PET_DELETED,
    ROLE_CHANGED,
    PERMISSION_CHANGED,
    ADOPTION_APPROVED,
    ADOPTION_REJECTED,
    ADOPTION_COMPLETED,
    SYSTEM_SETTING_CHANGED,
    OTHER
}