package com.furandfeathers.enums;

public enum NotificationType {
    SHELTER_APPROVED,
    SHELTER_REJECTED,
    SHELTER_SUSPENDED,
    PET_APPROVED,
    PET_REJECTED,
    APPLICATION_RECEIVED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    SYSTEM_MESSAGE,
    ACCOUNT_SUSPENDED,
    ACCOUNT_ACTIVATED,
    NEW_MESSAGE,
    NEW_COMMENT,
    NEW_LIKE,
    OTHER
}